# coding: utf-8

"""
    Fraud Detection API

    An API for providing fraud detection capabilities.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fd_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_default_route_get(self) -> None:
        """Test case for default_route_get

        Default Route
        """
        pass

    def test_extract_exif_data_exifdata_post(self) -> None:
        """Test case for extract_exif_data_exifdata_post

        Extract Exif Data
        """
        pass

    def test_healthcheck_healthcheck_get(self) -> None:
        """Test case for healthcheck_healthcheck_get

        Healthcheck
        """
        pass

    def test_perform_claim_deduction_predict_post(self) -> None:
        """Test case for perform_claim_deduction_predict_post

        Perform Claim Deduction
        """
        pass

    def test_reverse_internet_search_search_internet_post(self) -> None:
        """Test case for reverse_internet_search_search_internet_post

        Reverse Internet Search
        """
        pass

    def test_search_image_library_searchlibrary_post(self) -> None:
        """Test case for search_image_library_searchlibrary_post

        Search Image Library
        """
        pass


if __name__ == '__main__':
    unittest.main()
