# coding: utf-8

"""
    Fraud Detection API

    An API for providing fraud detection capabilities.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fd_api_client.models.library_image_with_score import LibraryImageWithScore

class TestLibraryImageWithScore(unittest.TestCase):
    """LibraryImageWithScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LibraryImageWithScore:
        """Test LibraryImageWithScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LibraryImageWithScore`
        """
        model = LibraryImageWithScore()
        if include_optional:
            return LibraryImageWithScore(
                id = '',
                image_s3_key = '',
                thumbnail_s3_key = '',
                filename = '',
                created_timestamp = '',
                size = 56,
                score = 1.337
            )
        else:
            return LibraryImageWithScore(
                id = '',
                image_s3_key = '',
                thumbnail_s3_key = '',
                filename = '',
                created_timestamp = '',
                size = 56,
                score = 1.337,
        )
        """

    def testLibraryImageWithScore(self):
        """Test LibraryImageWithScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
