# coding: utf-8

"""
    Fraud Detection API

    An API for providing fraud detection capabilities.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class LibraryImageWithScore(BaseModel):
    """
    A data model representing a library image with its corresponding score. Attributes:     image (LibraryImage): The library image.     score (float): The score associated with the image.
    """ # noqa: E501
    id: StrictStr
    image_s3_key: StrictStr
    thumbnail_s3_key: StrictStr
    filename: StrictStr
    created_timestamp: StrictStr
    size: StrictInt
    score: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["id", "image_s3_key", "thumbnail_s3_key", "filename", "created_timestamp", "size", "score"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LibraryImageWithScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LibraryImageWithScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "image_s3_key": obj.get("image_s3_key"),
            "thumbnail_s3_key": obj.get("thumbnail_s3_key"),
            "filename": obj.get("filename"),
            "created_timestamp": obj.get("created_timestamp"),
            "size": obj.get("size"),
            "score": obj.get("score")
        })
        return _obj


